const state={view:'dashboard',fornecedores:[],solicitacoes:[],selectedRequestId:null,lastEvaluation:new Map()};
const titles={dashboard:['Visão geral','Acompanhe o fluxo de compras e cotações.'],solicitacoes:['Solicitações','Consulte e opere as solicitações de compra.'],nova:['Nova solicitação','Crie uma solicitação e defina a estratégia de avaliação.'],fornecedores:['Fornecedores','Cadastre e consulte fornecedores participantes.'],sobre:['Sobre o projeto','Veja onde cada Design Pattern foi aplicado.'],detalhe:['Detalhes da solicitação','Cotações, avaliação e decisão de compra.']};
const content=document.getElementById('content');const pageTitle=document.getElementById('pageTitle');const pageSubtitle=document.getElementById('pageSubtitle');const supplierDialog=document.getElementById('supplierDialog');const quoteDialog=document.getElementById('quoteDialog');const approvalDialog=document.getElementById('approvalDialog');const rejectDialog=document.getElementById('rejectDialog');
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function money(v,c='BRL'){if(v===null||v===undefined)return'—';return new Intl.NumberFormat('pt-BR',{style:'currency',currency:c}).format(Number(v))}
function date(v){if(!v)return'—';return new Intl.DateTimeFormat('pt-BR').format(new Date(`${v}T12:00:00`))}
function dateTime(v){if(!v)return'—';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}
function statusLabel(s){return{RASCUNHO:'Rascunho',EM_COTACAO:'Em cotação',AGUARDANDO_APROVACAO:'Aguardando aprovação',APROVADA:'Aprovada',REJEITADA:'Rejeitada'}[s]||s}
function criterioLabel(v){return{MENOR_PRECO:'Menor preço',MENOR_PRAZO:'Menor prazo',CUSTO_BENEFICIO:'Custo-benefício'}[v]||v}
function toast(t,m='',type=''){const n=document.createElement('div');n.className=`toast ${type}`;n.innerHTML=`<strong>${esc(t)}</strong>${m?`<span>${esc(m)}</span>`:''}`;document.getElementById('toastContainer').appendChild(n);setTimeout(()=>n.remove(),4200)}
function err(r){if(!r?.data)return`Erro HTTP ${r?.status||''}`.trim();const d=r.data.detail||r.data.message||r.data.title;const e=r.data.errors?Object.values(r.data.errors).join(' · '):'';return[d,e].filter(Boolean).join(' — ')||`Erro HTTP ${r.status}`}
async function api(method,endpoint,body){const r=await window.compraflow.api.request(method,endpoint,body);if(!r.ok)throw new Error(err(r));return r.data}
function loading(){content.innerHTML='<div class="loading">Carregando...</div>'}
function setHeader(v){const[t,s]=titles[v]||titles.dashboard;pageTitle.textContent=t;pageSubtitle.textContent=s}
function setActiveNav(v){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
async function refreshData(){const[f,s]=await Promise.all([api('GET','/api/fornecedores'),api('GET','/api/solicitacoes')]);state.fornecedores=f||[];state.solicitacoes=s||[]}
async function go(view,o={}){state.view=view;if(o.id)state.selectedRequestId=Number(o.id);setHeader(view);setActiveNav(view==='detalhe'?'solicitacoes':view);loading();try{if(view!=='sobre')await refreshData();if(view==='dashboard')renderDashboard();if(view==='solicitacoes')renderSolicitacoes();if(view==='nova')renderNova();if(view==='fornecedores')renderFornecedores();if(view==='sobre')renderSobre();if(view==='detalhe')await renderDetalhe(state.selectedRequestId)}catch(e){content.innerHTML=`<div class="empty"><strong>Não foi possível carregar</strong>${esc(e.message)}</div>`;toast('Erro ao carregar dados',e.message,'error')}}
function requestTable(rows){if(!rows.length)return'<div class="empty"><strong>Nenhuma solicitação cadastrada</strong>Crie a primeira solicitação para iniciar o fluxo.</div>';return`<div class="table-wrap"><table><thead><tr><th>Código</th><th>Solicitante</th><th>Departamento</th><th>Critério</th><th>Status</th><th>Criada em</th></tr></thead><tbody>${rows.map(i=>`<tr><td><button class="link-button" data-request-id="${i.id}">${esc(i.codigo)}</button></td><td>${esc(i.solicitante)}</td><td>${esc(i.departamento)}</td><td>${esc(criterioLabel(i.criterioAvaliacao))}</td><td><span class="badge ${i.status}">${esc(statusLabel(i.status))}</span></td><td>${esc(dateTime(i.criadaEm))}</td></tr>`).join('')}</tbody></table></div>`}
function renderDashboard(){const c=state.solicitacoes.reduce((a,i)=>(a[i.status]=(a[i.status]||0)+1,a),{});const recent=[...state.solicitacoes].sort((a,b)=>b.id-a.id).slice(0,6);content.innerHTML=`<div class="cards"><div class="metric"><div class="label">Solicitações</div><div class="value">${state.solicitacoes.length}</div><div class="hint">Total cadastrado</div></div><div class="metric"><div class="label">Em cotação</div><div class="value">${c.EM_COTACAO||0}</div><div class="hint">Recebendo propostas</div></div><div class="metric"><div class="label">Aguardando aprovação</div><div class="value">${c.AGUARDANDO_APROVACAO||0}</div><div class="hint">Com fornecedor selecionado</div></div><div class="metric"><div class="label">Fornecedores</div><div class="value">${state.fornecedores.length}</div><div class="hint">Ativos para cotação</div></div></div><div class="section"><div class="section-head"><div><h2>Solicitações recentes</h2><p>Últimos processos de compra cadastrados.</p></div><button class="btn ghost small" data-go="solicitacoes">Ver todas</button></div>${requestTable(recent)}</div>`}
function renderSolicitacoes(){content.innerHTML=`<div class="section" style="margin-top:0"><div class="section-head"><div><h2>Todos os processos</h2><p>${state.solicitacoes.length} solicitação(ões) cadastrada(s).</p></div><button class="btn primary small" data-go="nova">＋ Nova solicitação</button></div>${requestTable(state.solicitacoes)}</div>`}
function renderNova(){content.innerHTML=`<form id="requestForm" class="form-card"><div class="form-grid two"><label>Solicitante<input name="solicitante" required maxlength="120" placeholder="Nome do solicitante"></label><label>Departamento<input name="departamento" required maxlength="100" placeholder="Ex.: TI, Financeiro, Compras"></label></div><label style="margin-top:16px">Justificativa<textarea name="justificativa" required maxlength="1000" rows="4" placeholder="Explique a necessidade da compra"></textarea></label><label style="margin-top:16px">Estratégia de avaliação<select name="criterioAvaliacao"><option value="MENOR_PRECO">Menor preço</option><option value="MENOR_PRAZO">Menor prazo</option><option value="CUSTO_BENEFICIO" selected>Custo-benefício</option></select></label><div class="section-head" style="padding-left:0;padding-right:0;margin-top:20px"><div><h2>Itens da solicitação</h2><p>Adicione um ou mais itens.</p></div><button type="button" class="btn ghost small" id="addItemButton">＋ Adicionar item</button></div><div id="itemsBox" class="items-box"></div><div class="form-actions"><button type="button" class="btn ghost" data-go="solicitacoes">Cancelar</button><button class="btn primary" type="submit">Criar solicitação</button></div></form>`;addItem()}
function addItem(){const box=document.getElementById('itemsBox');const r=document.createElement('div');r.className='item-row';r.innerHTML='<input data-field="descricao" required maxlength="180" placeholder="Descrição"><input data-field="quantidade" required type="number" min="1" value="1"><input data-field="unidade" required maxlength="20" value="UN"><input data-field="especificacao" maxlength="1000" placeholder="Especificação (opcional)"><button type="button" class="icon-btn remove-item">×</button>';box.appendChild(r)}
function renderFornecedores(){const rows=state.fornecedores.map(f=>`<tr><td><strong>${esc(f.razaoSocial)}</strong></td><td>${esc(f.cnpj)}</td><td>${esc(f.email)}</td><td><span class="badge">${f.ativo?'Ativo':'Inativo'}</span></td></tr>`).join('');content.innerHTML=`<div class="section" style="margin-top:0"><div class="section-head"><div><h2>Fornecedores ativos</h2><p>Empresas disponíveis para registrar propostas.</p></div><button class="btn primary small" id="newSupplierButton">＋ Novo fornecedor</button></div><div class="table-wrap"><table><thead><tr><th>Razão social</th><th>CNPJ</th><th>E-mail</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></div>`}
function actions(r){const a=[];if(r.status==='RASCUNHO')a.push('<button class="btn primary" id="openQuotePhaseButton">Abrir para cotação</button>');if(r.status==='EM_COTACAO')a.push('<button class="btn primary" id="evaluateButton">Avaliar cotações</button>');if(r.status==='AGUARDANDO_APROVACAO'){a.push('<button class="btn success" id="approveButton">Aprovar</button>');a.push('<button class="btn danger" id="rejectButton">Rejeitar</button>')}return a.join('')}
function quoteTable(qs,sel){if(!qs.length)return'<div class="empty"><strong>Nenhuma cotação recebida</strong>Abra o processo e registre ao menos três propostas.</div>';return`<div class="table-wrap"><table><thead><tr><th>Fornecedor</th><th>Total</th><th>Entrega</th><th>Pagamento</th><th>Validade</th><th></th></tr></thead><tbody>${qs.map(q=>`<tr><td>${esc(q.fornecedor)}</td><td>${money(q.totalOriginal,q.moeda)} <small>${q.moeda}</small></td><td>${q.prazoEntregaDias} dias</td><td>${q.prazoPagamentoDias} dias</td><td>${date(q.validade)}</td><td>${sel===q.id?'<span class="badge APROVADA">Selecionada</span>':''}</td></tr>`).join('')}</tbody></table></div>`}
async function renderDetalhe(id){const r=await api('GET',`/api/solicitacoes/${id}`);const qs=await api('GET',`/api/solicitacoes/${id}/cotacoes`);const ev=state.lastEvaluation.get(id);content.innerHTML=`<div class="detail-grid"><div><div class="detail-card"><div style="display:flex;justify-content:space-between"><div><h2 style="margin:0 0 5px">${esc(r.codigo)}</h2><span class="badge ${r.status}">${esc(statusLabel(r.status))}</span></div><button class="btn ghost small" data-go="solicitacoes">← Voltar</button></div><p style="color:var(--muted);margin:17px 0 0;line-height:1.6">${esc(r.justificativa)}</p><div class="action-row">${actions(r)}</div></div><div class="section"><div class="section-head"><div><h2>Itens solicitados</h2><p>${r.itens.length} item(ns)</p></div></div><div class="table-wrap"><table><thead><tr><th>Descrição</th><th>Qtd.</th><th>Unidade</th><th>Especificação</th></tr></thead><tbody>${r.itens.map(i=>`<tr><td>${esc(i.descricao)}</td><td>${i.quantidade}</td><td>${esc(i.unidade)}</td><td>${esc(i.especificacao||'—')}</td></tr>`).join('')}</tbody></table></div></div><div class="section"><div class="section-head"><div><h2>Cotações recebidas</h2><p>${qs.length} proposta(s) registrada(s).</p></div>${r.status==='EM_COTACAO'?'<button class="btn primary small" id="addQuoteButton">＋ Registrar cotação</button>':''}</div>${quoteTable(qs,r.cotacaoSelecionadaId)}</div>${ev?`<div class="winner"><strong>Resultado da avaliação</strong><div style="margin-top:7px">${esc(ev.fornecedorVencedor)} · ${money(ev.valorTotalBrl)} · ${ev.prazoEntregaDias} dia(s)</div><div style="color:var(--muted);font-size:12px;margin-top:5px">${esc(ev.justificativa)}</div></div>`:''}</div><aside class="detail-card"><h3>Dados do processo</h3><div class="meta-list"><div class="meta"><span>Solicitante</span><b>${esc(r.solicitante)}</b></div><div class="meta"><span>Departamento</span><b>${esc(r.departamento)}</b></div><div class="meta"><span>Estratégia</span><b>${esc(criterioLabel(r.criterioAvaliacao))}</b></div><div class="meta"><span>Valor selecionado</span><b>${money(r.valorSelecionadoBrl)}</b></div><div class="meta"><span>Nível exigido</span><b>${esc(r.nivelAprovacaoExigido||'—')}</b></div><div class="meta"><span>Aprovador</span><b>${esc(r.nivelAprovador||'—')}</b></div><div class="meta"><span>Criada em</span><b>${esc(dateTime(r.criadaEm))}</b></div></div></aside></div>`}
function renderSobre(){content.innerHTML='<div class="about-grid"><div class="pattern-card"><b>Singleton</b><p><code>MoneyRoundingPolicy</code> demonstra o Singleton clássico. Beans do Spring também usam escopo singleton por padrão.</p></div><div class="pattern-card"><b>Strategy</b><p>A seleção troca entre menor preço, menor prazo e custo-benefício sem alterar o fluxo principal.</p></div><div class="pattern-card"><b>Facade</b><p><code>CompraFacade</code> esconde services, repositories, câmbio, strategies e aprovação dos controllers.</p></div><div class="pattern-card"><b>Chain of Responsibility</b><p>A aprovação percorre Coordenador → Gerente → Diretor → Diretoria.</p></div></div><div class="section"><div class="section-head"><div><h2>Arquitetura desktop</h2><p>Electron gerencia o Spring Boot local.</p></div></div><div style="padding:18px"><div class="code">Electron Renderer\n  │ IPC seguro\n  ▼\nElectron Main\n  │ HTTP 127.0.0.1\n  ▼\nSpring Boot + JPA + H2 persistente</div><div class="action-row"><button class="btn ghost" id="openSwaggerButton">Abrir Swagger</button><button class="btn ghost" id="openLogsButton">Abrir log</button><button class="btn ghost" id="openDataButton">Pasta de dados</button></div></div></div>'}
function quoteDialogOpen(id){quoteDialog.querySelector('[name=solicitacaoId]').value=id;quoteDialog.querySelector('[name=fornecedorId]').innerHTML=state.fornecedores.map(f=>`<option value="${f.id}">${esc(f.razaoSocial)}</option>`).join('');const d=new Date();d.setDate(d.getDate()+15);quoteDialog.querySelector('[name=validade]').value=d.toISOString().slice(0,10);quoteDialog.showModal()}
async function runAction(fn,msg){try{await fn();toast(msg,'','success');await go('detalhe',{id:state.selectedRequestId})}catch(e){toast('Operação não concluída',e.message,'error')}}
content.addEventListener('click',e=>{const rb=e.target.closest('[data-request-id]');if(rb)return go('detalhe',{id:rb.dataset.requestId});const gb=e.target.closest('[data-go]');if(gb)return go(gb.dataset.go);if(e.target.closest('#addItemButton'))return addItem();if(e.target.closest('.remove-item')){const row=e.target.closest('.item-row');const box=document.getElementById('itemsBox');if(box.children.length>1)row.remove();else toast('A solicitação precisa ter ao menos um item.','','error');return}if(e.target.closest('#newSupplierButton'))return supplierDialog.showModal();if(e.target.closest('#addQuoteButton'))return quoteDialogOpen(state.selectedRequestId);if(e.target.closest('#openQuotePhaseButton'))return runAction(()=>api('POST',`/api/solicitacoes/${state.selectedRequestId}/abrir-cotacao`),'Solicitação aberta para cotação.');if(e.target.closest('#evaluateButton'))return runAction(async()=>{const x=await api('POST',`/api/solicitacoes/${state.selectedRequestId}/avaliar`);state.lastEvaluation.set(state.selectedRequestId,x)},'Cotações avaliadas e proposta selecionada.');if(e.target.closest('#approveButton')){approvalDialog.querySelector('[name=solicitacaoId]').value=state.selectedRequestId;return approvalDialog.showModal()}if(e.target.closest('#rejectButton')){rejectDialog.querySelector('[name=solicitacaoId]').value=state.selectedRequestId;return rejectDialog.showModal()}if(e.target.closest('#openSwaggerButton'))return window.compraflow.backend.openSwagger();if(e.target.closest('#openLogsButton'))return window.compraflow.backend.openLogs();if(e.target.closest('#openDataButton'))return window.compraflow.app.showDataFolder()});
content.addEventListener('submit',async e=>{if(e.target.id!=='requestForm')return;e.preventDefault();const f=new FormData(e.target);const itens=[...document.querySelectorAll('.item-row')].map(r=>({descricao:r.querySelector('[data-field=descricao]').value.trim(),quantidade:Number(r.querySelector('[data-field=quantidade]').value),unidade:r.querySelector('[data-field=unidade]').value.trim(),especificacao:r.querySelector('[data-field=especificacao]').value.trim()||null}));try{const c=await api('POST','/api/solicitacoes',{solicitante:f.get('solicitante').trim(),departamento:f.get('departamento').trim(),justificativa:f.get('justificativa').trim(),criterioAvaliacao:f.get('criterioAvaliacao'),itens});toast('Solicitação criada',c.codigo,'success');go('detalhe',{id:c.id})}catch(x){toast('Não foi possível criar',x.message,'error')}});
document.getElementById('supplierForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('POST','/api/fornecedores',{razaoSocial:f.get('razaoSocial').trim(),cnpj:f.get('cnpj').trim(),email:f.get('email').trim()});supplierDialog.close();e.target.reset();toast('Fornecedor cadastrado','','success');go('fornecedores')}catch(x){toast('Não foi possível cadastrar',x.message,'error')}});
document.getElementById('quoteForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),id=Number(f.get('solicitacaoId'));try{await api('POST',`/api/solicitacoes/${id}/cotacoes`,{fornecedorId:Number(f.get('fornecedorId')),valorProdutos:Number(f.get('valorProdutos')),frete:Number(f.get('frete')),moeda:f.get('moeda'),prazoEntregaDias:Number(f.get('prazoEntregaDias')),prazoPagamentoDias:Number(f.get('prazoPagamentoDias')),validade:f.get('validade')});quoteDialog.close();e.target.reset();toast('Cotação registrada','','success');go('detalhe',{id})}catch(x){toast('Não foi possível registrar',x.message,'error')}});
document.getElementById('approvalForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),id=Number(f.get('solicitacaoId'));try{await api('POST',`/api/solicitacoes/${id}/aprovar`,{nivelAprovador:f.get('nivelAprovador'),observacao:f.get('observacao').trim()||null});approvalDialog.close();e.target.reset();toast('Solicitação aprovada','','success');go('detalhe',{id})}catch(x){toast('Aprovação não concluída',x.message,'error')}});
document.getElementById('rejectForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),id=Number(f.get('solicitacaoId'));try{await api('POST',`/api/solicitacoes/${id}/rejeitar`,{motivo:f.get('motivo').trim()});rejectDialog.close();e.target.reset();toast('Solicitação rejeitada','','success');go('detalhe',{id})}catch(x){toast('Rejeição não concluída',x.message,'error')}});
document.addEventListener('click',e=>{const n=e.target.closest('[data-view]');if(n)go(n.dataset.view);const g=e.target.closest('[data-go]');if(g&&!content.contains(g))go(g.dataset.go)});document.getElementById('refreshButton').addEventListener('click',()=>go(state.view,{id:state.selectedRequestId}));window.compraflow.backend.onStopped(()=>{document.getElementById('backendDot').classList.add('off');document.getElementById('backendLabel').textContent='Backend interrompido';toast('Backend local foi encerrado','Reabra o CompraFlow para reiniciar.','error')});
(async()=>{const s=await window.compraflow.backend.status();document.getElementById('appVersion').textContent=`CompraFlow Desktop v${s.version}`;document.getElementById('backendLabel').textContent=s.running?'Backend local ativo':'Backend indisponível';document.getElementById('backendDot').classList.toggle('off',!s.running);await go('dashboard')})();
